
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: migrate_fedora_3_to_4_development


test:
  <<: *default
  database: migrate_fedora_3_to_4_test

production:
  <<: *default
  database: migrate_fedora_3_to_4_production
  username: migrate_fedora_3_to_4
  password: <%= ENV['MIGRATE_FEDORA_3_TO_4_DATABASE_PASSWORD'] %>
